[package]
name = "domain"
version.workspace = true
edition.workspace = true

[dependencies]
shared = { path = "../shared" }
uuid.workspace = true
serde.workspace = true
chrono.workspace = true
async-trait.workspace = true
anyhow.workspace = true
thiserror.workspace = true

